### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by firminochangani** [levibostian/Wendy-Android#26]
@levibostian adding tests would make developers more comfortable to use Wendy in production.

**Comment by levibostian** [comment]
Couldn't agree more 😄. 

At this time, I have the example app as the "tests" for the library while developing it. Tests are on the list. Thanks!

**Comment by levibostian** [comment]
Closing this issue and instead focusing on [this issue](https://github.com/levibostian/Wendy-Android/issues/50) to get the testing environment created first, then we will worry about writing the tests. 

Thanks @flowck for your continued support.
